spring:
  application:
    name: stock_info_svc
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080

logging:
  level:
    com.sahil.stock.info: DEBUG
    org.springframework.web: DEBUG

stock:
  api-url: ${STOCK_API_URL}
  api-key: ${STOCK_API_KEY}
